/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.suma.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the prueba service. Represents a row in the &quot;prueba_prueba&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.suma.model.impl.pruebaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.suma.model.impl.pruebaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see prueba
 * @see com.liferay.suma.model.impl.pruebaImpl
 * @see com.liferay.suma.model.impl.pruebaModelImpl
 * @generated
 */
@ProviderType
public interface pruebaModel extends BaseModel<prueba>, GroupedModel,
	ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a prueba model instance should use the {@link prueba} interface instead.
	 */

	/**
	 * Returns the primary key of this prueba.
	 *
	 * @return the primary key of this prueba
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this prueba.
	 *
	 * @param primaryKey the primary key of this prueba
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this prueba.
	 *
	 * @return the uuid of this prueba
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this prueba.
	 *
	 * @param uuid the uuid of this prueba
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the prueba ID of this prueba.
	 *
	 * @return the prueba ID of this prueba
	 */
	public long getPruebaId();

	/**
	 * Sets the prueba ID of this prueba.
	 *
	 * @param pruebaId the prueba ID of this prueba
	 */
	public void setPruebaId(long pruebaId);

	/**
	 * Returns the group ID of this prueba.
	 *
	 * @return the group ID of this prueba
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this prueba.
	 *
	 * @param groupId the group ID of this prueba
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this prueba.
	 *
	 * @return the company ID of this prueba
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this prueba.
	 *
	 * @param companyId the company ID of this prueba
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this prueba.
	 *
	 * @return the user ID of this prueba
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this prueba.
	 *
	 * @param userId the user ID of this prueba
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this prueba.
	 *
	 * @return the user uuid of this prueba
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this prueba.
	 *
	 * @param userUuid the user uuid of this prueba
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this prueba.
	 *
	 * @return the user name of this prueba
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this prueba.
	 *
	 * @param userName the user name of this prueba
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this prueba.
	 *
	 * @return the create date of this prueba
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this prueba.
	 *
	 * @param createDate the create date of this prueba
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this prueba.
	 *
	 * @return the modified date of this prueba
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this prueba.
	 *
	 * @param modifiedDate the modified date of this prueba
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the field1 of this prueba.
	 *
	 * @return the field1 of this prueba
	 */
	public int getField1();

	/**
	 * Sets the field1 of this prueba.
	 *
	 * @param field1 the field1 of this prueba
	 */
	public void setField1(int field1);

	/**
	 * Returns the field2 of this prueba.
	 *
	 * @return the field2 of this prueba
	 */
	public int getField2();

	/**
	 * Sets the field2 of this prueba.
	 *
	 * @param field2 the field2 of this prueba
	 */
	public void setField2(int field2);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.suma.model.prueba prueba);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.suma.model.prueba> toCacheModel();

	@Override
	public com.liferay.suma.model.prueba toEscapedModel();

	@Override
	public com.liferay.suma.model.prueba toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}