/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.jbaricot.formulario.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the formulario service. Represents a row in the &quot;formulario_formulario&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.jbaricot.formulario.model.impl.formularioModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.jbaricot.formulario.model.impl.formularioImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see formulario
 * @see com.jbaricot.formulario.model.impl.formularioImpl
 * @see com.jbaricot.formulario.model.impl.formularioModelImpl
 * @generated
 */
@ProviderType
public interface formularioModel extends BaseModel<formulario>, GroupedModel,
	ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a formulario model instance should use the {@link formulario} interface instead.
	 */

	/**
	 * Returns the primary key of this formulario.
	 *
	 * @return the primary key of this formulario
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this formulario.
	 *
	 * @param primaryKey the primary key of this formulario
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this formulario.
	 *
	 * @return the uuid of this formulario
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this formulario.
	 *
	 * @param uuid the uuid of this formulario
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the formulario ID of this formulario.
	 *
	 * @return the formulario ID of this formulario
	 */
	public long getFormularioId();

	/**
	 * Sets the formulario ID of this formulario.
	 *
	 * @param formularioId the formulario ID of this formulario
	 */
	public void setFormularioId(long formularioId);

	/**
	 * Returns the group ID of this formulario.
	 *
	 * @return the group ID of this formulario
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this formulario.
	 *
	 * @param groupId the group ID of this formulario
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this formulario.
	 *
	 * @return the company ID of this formulario
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this formulario.
	 *
	 * @param companyId the company ID of this formulario
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this formulario.
	 *
	 * @return the user ID of this formulario
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this formulario.
	 *
	 * @param userId the user ID of this formulario
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this formulario.
	 *
	 * @return the user uuid of this formulario
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this formulario.
	 *
	 * @param userUuid the user uuid of this formulario
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this formulario.
	 *
	 * @return the user name of this formulario
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this formulario.
	 *
	 * @param userName the user name of this formulario
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this formulario.
	 *
	 * @return the create date of this formulario
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this formulario.
	 *
	 * @param createDate the create date of this formulario
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this formulario.
	 *
	 * @return the modified date of this formulario
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this formulario.
	 *
	 * @param modifiedDate the modified date of this formulario
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the field1 of this formulario.
	 *
	 * @return the field1 of this formulario
	 */
	public int getField1();

	/**
	 * Sets the field1 of this formulario.
	 *
	 * @param field1 the field1 of this formulario
	 */
	public void setField1(int field1);

	/**
	 * Returns the field2 of this formulario.
	 *
	 * @return the field2 of this formulario
	 */
	public int getField2();

	/**
	 * Sets the field2 of this formulario.
	 *
	 * @param field2 the field2 of this formulario
	 */
	public void setField2(int field2);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.jbaricot.formulario.model.formulario formulario);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.jbaricot.formulario.model.formulario> toCacheModel();

	@Override
	public com.jbaricot.formulario.model.formulario toEscapedModel();

	@Override
	public com.jbaricot.formulario.model.formulario toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}